version: "3.9"

services:
  postgres:
    image: postgres:17.8
    container_name: jobsonmap-postgres
    restart: always
    environment:
      POSTGRES_USER: jobsonmap
      POSTGRES_PASSWORD: jobsonmap
      POSTGRES_DB: jobsonmap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: